### ISSUE TITLE
Verify and add tests for character as input for class constructors

### ISSUE THREAD

**Issue by zachary-foster** [ropenscilabs/taxa#14]
Hi @sckott, I was thinking that it would be useful if all of the classes allowed for character input when being initialized as well as objects as they currently do. I started doing this for `taxonomy` and therefore most of the others as well since the `taxonomy` constructor now calls their constructors to do the character to object conversion, but I bet there are edge cases still unhanded. 

For example, the following code is used in the tests of `taxonomy`: 

```r
> taxonomy(c("a", "b", "c"), c("a", "d"))
<Taxonomy>
  4 taxa: 1. a, 2. b, 3. d, 4. c
  4 edges: NA->1, 1->2, 1->3, 2->4
```

I did have to reduce the stringency of some of the constructors to do this, particularly `taxon` which required the rank and `hierarchy`, which used the rank to sort taxa. I modified `hierarchy` to only sort taxa when all had ranks and otherwise retain input order.

Is all this OK with you?

**Comment by sckott** [comment]
Probably. Can you point me to where the change is in the code? is this an example of the change https://github.com/ropenscilabs/taxa/blob/issue-9/R/taxa-taxonomy.R#L28-L30

**Comment by zachary-foster** [comment]
I think this commit has all of the changes to the class constructors:

https://github.com/ropenscilabs/taxa/commit/8516219d6355954b75ea47ec3dd103b4345dc30a

**Comment by sckott** [comment]
yeah, looks good!

**Comment by zachary-foster** [comment]
Cool, this seems to be done then.
