### ISSUE TITLE
New utility functions

### ISSUE THREAD

**Issue by zachary-foster** [ropenscilabs/taxa#15]
There are a few "utility" functions I am thinking about adding in the same family as `subtaxa`, `supertaxa`, and `roots`. 

## `tips` or `leaves` 

This would return all the taxa with no subtaxa. It would be useful when transforming a `taxonomy` into a `hierarchies`. 

Which name do you like better? `leaves` is consistent with `roots` and `stems`, but `tips` is shorter...

## `stems` 

This would return only taxa between a root (`NA`) and the first taxon with more than one subtaxon. I find I often want to quickly remove these taxa since their information is not needed in many contexts (e.g. you have a dataset with only animals, but you still have "cellular organisms; Eukaryota; Opisthokonta" in front of everything.

**Comment by sckott** [comment]
Nice, both sound good. 

I like `leaves` over `tips`, as you said more consistent with other names

`stems` sounds good

**Comment by zachary-foster** [comment]
This is done now. I just realized I made the changed on the issue-9 branch. I intended to make another branch. 

If they look good to you I will close this.

**Comment by sckott** [comment]
that's okay, yeah, looks good to me.

**Comment by zachary-foster** [comment]
Nice
