### ISSUE TITLE
Finish overview vignette

### ISSUE THREAD

**Issue by zachary-foster** [ropenscilabs/taxa#36]
I think we should have a solid introduction vignette that briefly demonstrates the main functionality of the package before CRAN. Eventually, a few more vignettes that deal with things in more detail would be good, but those can be done later?

**Comment by sckott** [comment]
Yep, the 1 good intro vignette is good for this milestone

**Comment by zachary-foster** [comment]
Hey @sckott, can you take a look at the vingette and see how you like it? Thanks

**Comment by sckott** [comment]
yep, will do

**Comment by sckott** [comment]
Looks good to me!

**Comment by zachary-foster** [comment]
Cool, thanks!
