### ISSUE TITLE
"TaxonAuthority" class?

### ISSUE THREAD

**Issue by zachary-foster** [ropenscilabs/taxa#43]
Hi @sckott, I notice that the `taxon` man pages mention a `TaxonAuthority` object and the print method seems to expect one, but I do not see the code for one. Should there be such a class? It would be consistent with name, rank, and id, but I am not sure what we would gain by making it a class vs just a character. Do we want to associate the authority with a database for example?

**Comment by sckott** [comment]
let's just keep it as a character string, I can make a change for that.
